language: objective-c
osx_image: xcode11.3
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - xcodebuild -workspace ui_mac.xcworkspace -scheme ui_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
