language: objective-c
osx_image: xcode10
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - git submodule update --init --recursive
  - xcodebuild -project ui_mac_tests/ui_mac_tests.xcodeproj -scheme ui_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
